### ISSUE TITLE
Test.py -- unexpected input size

### ISSUE THREAD

**Issue by TheFrostyboss** [hangzhaomit/semantic-segmentation-pytorch#14]
Hi,

I'm trying to use the test.py script, but I'm getting an input.size error. Reportedly, input.size[1] should be 3, but the 384 (presumably imgSize) is being passed there instead. Any thoughts?

```
bash-4.1$ python test.py --ckpt ./ckpt/ --test_img "./data/ADEChallengeData2016/images/training/ADE_train_00000001.jpg" --id baseline-resnet34_dilated8-psp_bilinear --arch_decoder psp_bilinear --visualize VISUALIZE --batch_size 1
Namespace(arch_decoder='psp_bilinear', arch_encoder='resnet34_dilated8', batch_size=1, ckpt='./ckpt/', fc_dim=512, id='baseline-resnet34_dilated8-psp_bilinear', imgSize=384, num_class=150, num_val=-1, result='.', segSize=-1, suffix='_best.pth', test_img='./data/ADEChallengeData2016/images/training/ADE_train_00000001.jpg', visualize='VISUALIZE')
Loading weights for net_encoder
Loading weights for net_decodertar
/apps/python/2.7.11/gcc-5.3.0/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
Traceback (most recent call last):
  File "test.py", line 162, in <module>
    main(args)
  File "test.py", line 108, in main
    test(nets, args)
  File "test.py", line 85, in test
    pred = forward_test_multiscale(nets, img, args)
  File "test.py", line 36, in forward_test_multiscale
    pred_scale = net_decoder(net_encoder(input_img),
  File "/apps/pytorch/0.2.0/python-2.7_gcc-5.3_cuda-8.0_cudnn-6.0/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "./scripts/models.py", line 221, in forward
    x = self.relu1(self.bn1(self.conv1(x)))
  File "/apps/pytorch/0.2.0/python-2.7_gcc-5.3_cuda-8.0_cudnn-6.0/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/apps/pytorch/0.2.0/python-2.7_gcc-5.3_cuda-8.0_cudnn-6.0/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/apps/pytorch/0.2.0/python-2.7_gcc-5.3_cuda-8.0_cudnn-6.0/lib/python2.7/site-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: Need input.size[1] == 3 but got 384 instead.

```

**Comment by hangzhaomit** [comment]
please checkout the new demo script. @TheFrostyboss
