### ISSUE TITLE
RuntimeError: argument 1 (padding) must be tuple of int but got tuple of (float, float)

### ISSUE THREAD

**Issue by Tramac** [hangzhaomit/semantic-segmentation-pytorch#3]
when I run the train.py with python 3.6, this error appeared, why?

/home/xxx/.pyenv/versions/anaconda3-4.4.0/bin/python /home/xxx/semantic-segmentation-pytorch/train.py
samples: 20210
samples: 64
1 Epoch = 1263 iters
Evaluating at 0 epochs...
Traceback (most recent call last):
  File "/home/xxx/semantic-segmentation-pytorch/train.py", line 400, in <module>
    main(args)
  File "/home/xxx/semantic-segmentation-pytorch/train.py", line 276, in main
    evaluate(nets, loader_val, history, 0, args)
  File "/home/xxx/semantic-segmentation-pytorch/train.py", line 133, in evaluate
    pred, err = forward_with_loss(nets, batch_data, args, is_train=False)
  File "/home/xxx/semantic-segmentation-pytorch/train.py", line 35, in forward_with_loss
    pred = net_decoder(net_encoder(input_img))
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in ____call____
    result = self.forward(*input, **kwargs)
  File "/home/xxx/semantic-segmentation-pytorch/models.py", line 175, in forward
    x = self.features(x)
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in ____call____
    result = self.forward(*input, **kwargs)
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in ____call____
    result = self.forward(*input, **kwargs)
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in ____call____
    result = self.forward(*input, **kwargs)
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torchvision-0.1.9-py3.6.egg/torchvision/models/resnet.py", line 41, in forward
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in ____cal__l__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/home/xxx/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/nn/functional.py", line 51, in conv2d
    _pair(0), groups, torch.backends.cudnn.benchmark, torch.backends.cudnn.enabled)
RuntimeError: argument 1 (padding) must be tuple of int but got tuple of (float, float)

**Comment by jacktkk** [comment]
Hi man, did u ever meet this error 
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:87
