### ISSUE TITLE
train.py's problem

### ISSUE THREAD

**Issue by jacktkk** [hangzhaomit/semantic-segmentation-pytorch#4]
Hi~man 
when I run the python train.py it broken and I don't know the reason.
I will be appreciate if u can help me.

Evaluating at 0 epochs...
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=87 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 400, in <module>
    main(args)
  File "train.py", line 277, in main
    evaluate(nets, loader_val, history, 0, args)
  File "train.py", line 135, in evaluate
    pred, err = forward_with_loss(nets, batch_data, args, is_train=False)
  File "train.py", line 35, in forward_with_loss
    pred = net_decoder(net_encoder(input_img))
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 56, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 67, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 30, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim)
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 25, in scatter
    return scatter_map(inputs)
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 18, in scatter_map
    return tuple(zip(*map(scatter_map, obj)))
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return Scatter(target_gpus, dim=dim)(obj)
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 60, in forward
    outputs = comm.scatter(input, self.target_gpus, self.chunk_sizes, self.dim, streams)
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/cuda/comm.py", line 159, in scatter
    with torch.cuda.device(device), torch.cuda.stream(stream):
  File "/home/t/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 128, in __enter__
    torch._C._cuda_setDevice(self.idx)
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:87

**Comment by jacktkk** [comment]
I wish to know where can I find the net_decoder & net_encoder
