### ISSUE TITLE
python train.py is stuck at evaluate(nets, loader_val, history, 0, args)

### ISSUE THREAD

**Issue by danzschulman** [hangzhaomit/semantic-segmentation-pytorch#6]
When I run python.py  it writes:

Namespace(arch_decoder='c1bilinear', arch_encoder='resnet34_dilated8', batch_size_per_gpu=16, beta1=0.9, ckpt='./ckpt', ckpt_epoch=5, disp_iter=20, eval_epoch=1, fc_dim=512, fix_bn=0, flip=1, id='baseline', imgSize=384, list_train='./data/ADE20K_object150_train.txt', list_val='./data/ADE20K_object150_val.txt', lr_decoder=0.001, lr_encoder=0.0001, lr_step=20, num_epoch=50, num_gpus=2, num_val=64, optim='SGD', root_img='./data/ADEChallengeData2016/images', root_seg='./data/ADEChallengeData2016/annotations', seed=1234, segDepth=150, segSize=384, vis='./vis', weight_decay=0.0001, weights_decoder='', weights_encoder='', workers=16)
Model ID: baseline-resnet34_dilated8-c1bilinear-ngpus2-batchSize32-imgSize384-segSize384-lr_encoder0.0001-lr_decoder0.001-epoch50-step20-decay0.0001
\# samples: 20210
\# samples: 64
1 Epoch = 631 iters
Evaluating at 0 epochs...

and then stuck for hours without writing anything.
When I ctrl+c it says:

^CProcess Process-2:
Traceback (most recent call last):
  File "train.py", line 403, in <module>
    main(args)
  File "train.py", line 280, in main
    evaluate(nets, loader_val, history, 0, args)
  File "train.py", line 132, in evaluate
    for i, batch_data in enumerate(loader):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 195, in __next__
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/root/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 34, in _worker_loop
    r = index_queue.get()
  File "/root/anaconda3/lib/python3.6/multiprocessing/queues.py", line 342, in get
    res = self._reader.recv_bytes()
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
    idx, batch = self.data_queue.get()
KeyboardInterrupt
  File "/root/anaconda3/lib/python3.6/multiprocessing/queues.py", line 342, in get
    res = self._reader.recv_bytes()
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/root/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

which means it stucks on

evaluate(nets, loader_val, history, 0, args)

and specifically at

for i, batch_data in enumerate(loader):

and

chunk = read(handle, remaining)

Any ideas?

**Comment by hangzhaomit** [comment]
@danzschulman code has updated a lot since then, please try again, thanks.
